# Generated by Django 4.0.1 on 2022-01-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='class_type',
            field=models.CharField(choices=[('Gi Class (Beginners)', 'GI'), ('NoGi Class (Beginners)', 'NOGI'), ('Gi Class (Mixed Levels)', 'GIMIX'), ('NoGi Class (Mixed Levels)', 'NOGIMIX'), ('Open Mat', 'OPEN'), ('Sparring Class', 'SPARRING'), ('Wrestling', 'WRESTLING')], max_length=255),
        ),
    ]
