# Generated by Django 3.2.7 on 2021-10-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='class_type',
            field=models.CharField(choices=[('GI', 'Gi Class'), ('NOGI', 'NoGi Class')], default='GI', max_length=12),
            preserve_default=False,
        ),
    ]
