# Generated by Django 4.0.1 on 2022-01-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_alter_lesson_class_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-time']},
        ),
    ]
