# Generated by Django 4.0.1 on 2022-01-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(blank=True, upload_to='static/thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='video.difficulty')),
                ('section', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='video.section')),
            ],
        ),
    ]
