# Generated by Django 4.0.1 on 2022-01-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_techniqueoftheweek_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniqueoftheweek',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
