# Generated by Django 3.2.7 on 2021-10-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_membership_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
